<!-- Footer -->
<footer class="page-footer info-color darken-1" if="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-md-offset-1">
        <p class="white-text center-on-small-only">CONTACT ME</p>
        <a href="mailto:joncromie@gmail.com?" target="_top">joncromie@gmail.com</a>
        <!-- <p class="white-text center-on-small-only"></p> -->
        <!-- <a href="http://mdbootstrap.com/getting-started/" class="btn btn-danger waves-effect waves-light">Get started!</a> -->

      </div>
      <hr class="hidden-lg hidden-md">

      <div class="col-md-2">
        <p class="white-text center-on-small-only">THANKS TO</p>
        <ul>
          <!-- <li><a href="#" data-toggle="modal" data-target="#myModal" class="grey-text text-lighten-3" href="#!">Contact us</a>
          </li> -->
          <li><a class="grey-text text-lighten-3" href="http://mdbootstrap.com/" target="_blank">MDbootstrap.com</a>
          </li>
          <li><a class="grey-text text-lighten-3" href="https://unsplash.com" target="_blank">Unsplash</a>
          </li>


        </ul>
      </div>
      <hr class="hidden-lg hidden-md">

      <div class="col-md-3 text-center">
        <p class="white-text text-center"> STAY IN TOUCH</p>
        <a target="_blank" href="https://www.facebook.com/JonathanCromie" class="btn-floating btn-large fb-bg waves-effect waves-light"><i class="fa fa-facebook"> </i></a>
        <a target="_blank" href="https://twitter.com/joncromie" class="btn-floating btn-large tw-bg waves-effect waves-light"><i class="fa fa-twitter"> </i></a>
        <a target="_blank" href="https://plus.google.com/u/0/+JonathanCromie" class="btn-floating btn-large gplus-bg waves-effect waves-light"><i class="fa fa-google-plus"> </i></a>
        <a target="_blank" href="https://www.linkedin.com/profile/view?id=AAIAAA2lZ2MBgPNRAIUIsQWpyGwQI3NJML3dPYE&trk=nav_responsive_tab_profile" class="btn-floating btn-large li-bg waves-effect waves-light"><i class="fa fa-linkedin"> </i></a>
        <a target="_blank" href="https://github.com/jonathancromie" class="btn-floating btn-large gh-bg waves-effect waves-light"><i class="fa fa-github"> </i></a>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <div class="col-md-10 col-md-offset-1"> © 2015 Copyright <a href="http://www.jonathancromie.azurewebsites.net">Jonathan Cromie </a>
      </div>
    </div>
  </div>
</footer>
