<!-- Navigation -->
<nav class="navbar z-depth-2 info-color">
  <div class="container ">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand waves-effect waves-light" href="index.php">Coffee Recipes</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="#products" class="waves-effect waves-light">Products <span class="sr-only">(current)</span></a>
        </li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" role="button" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="savoury.php">Savoury</a>
            </li>
            <li><a href="desserts.php">Desserts</a>
            </li>
            <li><a href="beverages.php">Beverages</a>
            </li>
            <!-- <li class="divider"></li>
            <li><a href="#footer">Footer</a>
            </li> -->
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right waves-effect waves-light" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
          <button type="button" class="btn btn-info">
            <span class="glyphicon glyphicon-search"></span> Search
          </button>
        </div>
      </form>
    </div>
  </div>
</nav>
